### ISSUE TITLE
Главная: по дизайну и нет;

### ISSUE THREAD

**Issue by Janyell** [MyBeautyTeam/EverPay#10]
Не по дизайну: при загрузке цифры в меню много раз мигают, то показывают реальное число, то 0, перед тем, как устанавливается верное значение. Плюс несколько раз на этом моменте приложение аварийно завершалось (может, это только мой телефон не выдерживал :( )

По дизайну: Можно как-то выровнять расстояние от края текста в списке? Чтобы "для Жени" было так же далеко от линии, как и однострочный текст. Плюс можно ли убрать последнюю линию? 
![-oulnu_1zqm](https://cloud.githubusercontent.com/assets/6627219/7757490/72a3c78a-000b-11e5-86de-81dfa02d1c47.jpg)

P.S. Хотелось бы не стандартную загрузку :)

**Comment by pashna** [comment]
1) Все, что не по дизайну - сделал)
2) По дизайну. Нижнюю черту убрал, но мне показалось, что с ней лучше. 
По поводу отступа:
если сделать единый отступ, то у всех элементов будет разная высота, что смотрится, мягко говоря, так себе) Давай я фиксирую минимальную ширину отступа, но фиксировать ее не буду, тогда не будет неприятных наездов на линию?

**Comment by pashna** [comment]
Не пойму, как прицепить фотку))

**Comment by pashna** [comment]
Отправлю vk

**Comment by pashna** [comment]
И ещё, мне показалось, что с нижней плоской лучше, ну или привык просто)
