### ISSUE TITLE
Создание группы: по дизайну;

### ISSUE THREAD

**Issue by Janyell** [MyBeautyTeam/EverPay#12]
Вопросы и предложения:
1) У кнопок 14 шрифт?
2) Важно! На всех экранам серый и иные цвета обозначали, как должна выглядеть кнопка в разных состояниях. Поэтому я против всех серых кнопок. Если две кнопки рядом, можно добавить разделитель, как вариант, хотя я думаю, что и без него будет не плохо, но не серый цвет.
3) Название группы с краю, название счета по центру. Предлагаю прийти к общему знаменателю.
4) Кнопка "Готово" внизу не капсом, не продублирована сверху. Предлагаю на всех страницах продублировать и там, и там, поскольку всем по разному удобнее. 
Например, когда добавляла счета очень не хватало кнопки готово внизу. 
5) Переход на страницу добавления участников: заголовок меняется, при создании счета нет. Мелочи, но заметно.

**Comment by pashna** [comment]
4) Предлагаю оставить как есть. Страница добавления счёта итак перегружена, туда нельзя больше кнопок( Если хотим общий стандарт, давайте откажемся от кнопки. 
Я за то, чтобы оставить все как есть)
