### ISSUE TITLE
Группа: по дизайну;

### ISSUE THREAD

**Issue by Janyell** [MyBeautyTeam/EverPay#14]
Хотелось бы немного изменить вид кнопок, чтобы они стали больше похожи на первоначальный дизайн, плюс вопрос: кастомизации не будет? Мы вроде хотели, чтобы кнопки счетов, где мы есть подсвечивались по-одному, а остальные по-другому? 
Про серые кнопки не повторяюсь.

P.S.: Цвет подсветки, когда мы тянем вниз, можно как-то изменить? У меня стандартный оранжевый(

**Comment by Taniy** [comment]
Кастомизации точно нет,  пока или не пока,  Не знаю

**Comment by Taniy** [comment]
Оранжевый,  хахахах

**Comment by pashna** [comment]
Подсветку убрал совсем на устройствах ниже 5.0

**Comment by pashna** [comment]
Про подсветку не понял, объясни)

**Comment by Janyell** [comment]
Забыли про подсветку - везде оранжевый)

**Comment by pashna** [comment]
Нет, я про другую подсветку, в расчёте)
