### ISSUE TITLE
Нужно больше данных

### ISSUE THREAD

**Issue by pashna** [MyBeautyTeam/EverPay#15]
Нужен запросик, который вернет из чего сформировалась сумма, которую пользователь должен, или ему должны.
Я думаю, у тебя уже есть этот запрос, просто ты мне его не даешь) 
Название счета, баланс в этом счете (+/-)
Думаю, лично я объясню куда лучше, но пусть задача повесит)

**Comment by Janyell** [comment]
Я примерно поняла, но, если вживую объяснишь, будет лучше)
